import { Money } from '../money/money';
import { isSealed } from '../visibility/seal';

/**
 * Purchase aggregate: one state machine whose early states are intent-shaped
 * ("may I buy this?") and late states are transaction-shaped ("I spent this").
 *
 *   DRAFT ──► PENDING_APPROVAL ──► APPROVED ──► COMPLETED ──► REFUNDED
 *     │              │                 │            │
 *     │              ├──► DENIED       └──► CANCELLED
 *     │              └──► CANCELLED
 *     └──► COMPLETED   (approval-exempt direct log)
 *
 * Every transition returns the next snapshot plus an append-only event draft.
 * All functions are pure; time is always passed in.
 */

export type PurchaseState =
	'draft' | 'pending_approval' | 'approved' | 'denied' | 'cancelled' | 'completed' | 'refunded';

export interface Purchase {
	id: string;
	workspaceId: string;
	memberId: string;
	state: PurchaseState;
	itemName: string;
	note: string | null;
	categoryId: string | null;
	merchantId: string | null;
	requestedAmount: Money;
	approvedAmount: Money | null;
	finalAmount: Money | null;
	sealedUntil: Date | null;
	sealedFromMemberIds: string[];
	requestedAt: Date | null;
	decidedAt: Date | null;
	completedAt: Date | null;
	lastNudgedAt: Date | null;
	nudgeCount: number;
	/** Set when this purchase was generated by a recurring rule. */
	recurringRuleId: string | null;
	/** Set on refund child rows: the completed purchase being adjusted. */
	parentPurchaseId: string | null;
	/** Snapshot of routing at request time; never re-resolved while pending. */
	approverMemberIds: string[];
}

export class PurchaseStateError extends Error {
	constructor(message: string) {
		super(message);
		this.name = 'PurchaseStateError';
	}
}

export interface TransitionEvent {
	fromState: PurchaseState | null;
	toState: PurchaseState;
	actorMemberId: string | null;
	reason: string | null;
	amountSnapshot: Money | null;
	at: Date;
	/** Set only by unseal paths: members who were concealed and may now see it. */
	sealOpenedRecipients?: string[];
}

export interface TransitionResult {
	purchase: Purchase;
	event: TransitionEvent;
}

function assertState(p: Purchase, allowed: PurchaseState[], action: string): void {
	if (!allowed.includes(p.state)) {
		throw new PurchaseStateError(`Cannot ${action} a purchase in state '${p.state}'`);
	}
}

function event(
	p: Purchase,
	to: PurchaseState,
	actorMemberId: string | null,
	at: Date,
	reason: string | null = null,
	amountSnapshot: Money | null = null
): TransitionEvent {
	return { fromState: p.state, toState: to, actorMemberId, reason, amountSnapshot, at };
}

/** DRAFT → PENDING_APPROVAL. Approver set must already be resolved and non-empty. */
export function requestApproval(
	p: Purchase,
	approverMemberIds: string[],
	now: Date
): TransitionResult {
	assertState(p, ['draft'], 'request approval for');
	if (approverMemberIds.length === 0) {
		throw new PurchaseStateError('Cannot request approval with no approvers');
	}
	return {
		purchase: {
			...p,
			state: 'pending_approval',
			approverMemberIds: [...approverMemberIds],
			requestedAt: now
		},
		event: event(p, 'pending_approval', p.memberId, now, null, p.requestedAmount)
	};
}

/** DRAFT → APPROVED without an approver: the approval-exempt intent path. */
export function autoApprove(p: Purchase, now: Date, reason: string): TransitionResult {
	assertState(p, ['draft'], 'auto-approve');
	return {
		purchase: { ...p, state: 'approved', approvedAmount: p.requestedAmount, decidedAt: now },
		event: event(p, 'approved', null, now, reason, p.requestedAmount)
	};
}

/** PENDING_APPROVAL → APPROVED (or → COMPLETED when re-approving an overage). */
export function approve(p: Purchase, actorMemberId: string, now: Date): TransitionResult {
	assertState(p, ['pending_approval'], 'approve');
	if (!p.approverMemberIds.includes(actorMemberId)) {
		throw new PurchaseStateError('Only a designated approver can approve this purchase');
	}
	// An overage re-approval carries the already-spent final amount: approving
	// it completes the purchase, since the money is out the door.
	if (p.finalAmount !== null) {
		return {
			purchase: {
				...p,
				state: 'completed',
				approvedAmount: p.finalAmount,
				decidedAt: now,
				completedAt: p.completedAt ?? now
			},
			event: event(p, 'completed', actorMemberId, now, 'overage approved', p.finalAmount)
		};
	}
	return {
		purchase: { ...p, state: 'approved', approvedAmount: p.requestedAmount, decidedAt: now },
		event: event(p, 'approved', actorMemberId, now, null, p.requestedAmount)
	};
}

/** PENDING_APPROVAL → DENIED. */
export function deny(
	p: Purchase,
	actorMemberId: string,
	reason: string | null,
	now: Date
): TransitionResult {
	assertState(p, ['pending_approval'], 'deny');
	if (!p.approverMemberIds.includes(actorMemberId)) {
		throw new PurchaseStateError('Only a designated approver can deny this purchase');
	}
	return {
		purchase: { ...p, state: 'denied', decidedAt: now },
		event: event(p, 'denied', actorMemberId, now, reason)
	};
}

/** DRAFT | PENDING_APPROVAL | APPROVED → CANCELLED, by the requester. */
export function cancel(p: Purchase, actorMemberId: string, now: Date): TransitionResult {
	assertState(p, ['draft', 'pending_approval', 'approved'], 'cancel');
	if (actorMemberId !== p.memberId) {
		throw new PurchaseStateError('Only the requester can cancel a purchase');
	}
	return {
		purchase: { ...p, state: 'cancelled' },
		event: event(p, 'cancelled', actorMemberId, now)
	};
}

/** Final exceeds approved by more than the workspace's re-approval threshold? */
export function needsReapproval(approved: Money, final: Money, thresholdPct: number): boolean {
	if (!Number.isSafeInteger(thresholdPct) || thresholdPct < 0) {
		throw new PurchaseStateError(`Invalid re-approval threshold: ${thresholdPct}`);
	}
	// final > approved * (1 + pct/100), in exact integer arithmetic.
	return final.minor * 100n > approved.minor * BigInt(100 + thresholdPct);
}

/**
 * Complete with a final amount and date.
 * DRAFT → COMPLETED is the approval-exempt direct-log path.
 * APPROVED → COMPLETED, unless the final overshoots the approved amount by more
 * than thresholdPct — then it returns to PENDING_APPROVAL for re-approval,
 * carrying the attempted final amount. Under-spending never re-approves.
 */
export function complete(
	p: Purchase,
	actorMemberId: string,
	final: { amount: Money; at: Date },
	thresholdPct: number,
	now: Date
): TransitionResult {
	assertState(p, ['draft', 'approved'], 'complete');
	if (actorMemberId !== p.memberId) {
		throw new PurchaseStateError('Only the requester can complete a purchase');
	}
	if (final.amount.isNegative || final.amount.isZero) {
		throw new PurchaseStateError('Final amount must be positive');
	}
	// Overage re-approval only applies where approval applied: an auto-approved
	// purchase (exempt or recurring) has no approver snapshot and nobody to ask.
	if (
		p.state === 'approved' &&
		p.approverMemberIds.length > 0 &&
		needsReapproval(p.approvedAmount!, final.amount, thresholdPct)
	) {
		return {
			purchase: {
				...p,
				state: 'pending_approval',
				finalAmount: final.amount,
				completedAt: final.at,
				requestedAt: now,
				lastNudgedAt: null,
				nudgeCount: 0
			},
			event: event(p, 'pending_approval', actorMemberId, now, 'overage', final.amount)
		};
	}
	return {
		purchase: { ...p, state: 'completed', finalAmount: final.amount, completedAt: final.at },
		event: event(p, 'completed', actorMemberId, now, null, final.amount)
	};
}

export interface PurchaseEdit {
	itemName?: string;
	requestedAmount?: Money;
	categoryId?: string | null;
	note?: string | null;
}

/**
 * Edit item/amount/category while DRAFT, PENDING_APPROVAL, or APPROVED.
 * Editing an APPROVED purchase's substance invalidates the approval and
 * returns it to PENDING_APPROVAL. Note-only edits never invalidate.
 */
export function edit(
	p: Purchase,
	actorMemberId: string,
	changes: PurchaseEdit,
	now: Date
): TransitionResult {
	assertState(p, ['draft', 'pending_approval', 'approved'], 'edit');
	if (actorMemberId !== p.memberId) {
		throw new PurchaseStateError('Only the requester can edit a purchase');
	}
	const substantive =
		(changes.itemName !== undefined && changes.itemName !== p.itemName) ||
		(changes.requestedAmount !== undefined && !changes.requestedAmount.equals(p.requestedAmount)) ||
		(changes.categoryId !== undefined && changes.categoryId !== p.categoryId);

	const next: Purchase = {
		...p,
		itemName: changes.itemName ?? p.itemName,
		requestedAmount: changes.requestedAmount ?? p.requestedAmount,
		categoryId: changes.categoryId === undefined ? p.categoryId : changes.categoryId,
		note: changes.note === undefined ? p.note : changes.note
	};

	if (p.state === 'approved' && substantive) {
		if (p.approverMemberIds.length === 0) {
			throw new PurchaseStateError('Cannot invalidate approval with no approvers to re-approve');
		}
		return {
			purchase: {
				...next,
				state: 'pending_approval',
				approvedAmount: null,
				requestedAt: now,
				lastNudgedAt: null,
				nudgeCount: 0
			},
			event: event(
				p,
				'pending_approval',
				actorMemberId,
				now,
				'edited after approval',
				next.requestedAmount
			)
		};
	}
	return {
		purchase: next,
		event: event(next, next.state, actorMemberId, now, 'edited', next.requestedAmount)
	};
}

/** COMPLETED → REFUNDED once cumulative refunds cover the final amount. */
export function markRefunded(p: Purchase, actorMemberId: string, now: Date): TransitionResult {
	assertState(p, ['completed'], 'refund');
	// A refund on a sealed purchase would leak it through the numbers.
	if (isSealed(p, now)) {
		throw new PurchaseStateError('Sealed purchases cannot be refunded until the seal opens');
	}
	return {
		purchase: { ...p, state: 'refunded' },
		event: event(p, 'refunded', actorMemberId, now, null, p.finalAmount)
	};
}
