/**
 * Generate the demo build's route tree.
 *
 * The demo is the same app with a different driving adapter, but two things
 * make it impossible to build straight from `src/routes`: SvelteKit will not
 * let a static build contain a `+page.server.ts`, and the routes outside the
 * demo's scope (auth, MCP, the LLM endpoints) are server-only by nature.
 *
 * So rather than mutate the real route tree, this writes a parallel one at
 * `.demo/routes` containing only the demo's routes, with each
 * `+page.server.ts` replaced by a generated `+page.ts` that binds the very
 * same `handlers.ts` to a browser context. `vite.config.ts` points
 * `kit.files.routes` here when DEMO=1.
 *
 *   bun scripts/demo-build.ts
 */
import { cp, mkdir, readdir, readFile, rm, writeFile, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '');
const SRC = `${ROOT}/src/routes`;
const OUT = `${ROOT}/.demo/routes`;

/**
 * Routes the demo ships. Everything absent is excluded by construction rather
 * than by filtering, so adding a route to the demo is a deliberate act.
 */
export const DEMO_ROUTES = [
	'w/[workspace]/purchases',
	'w/[workspace]/purchases/new',
	'w/[workspace]/purchases/[id]',
	'w/[workspace]/buckets',
	'w/[workspace]/income',
	'w/[workspace]/analytics',
	'w/[workspace]/calendar',
	'w/[workspace]/recurring',
	'w/[workspace]/settings/categories',
	'w/[workspace]/settings/help',
	'w/[workspace]/statement',
	'w/[workspace]'
];

/** Files that only make sense with a server behind them. */
const SERVER_FILE = /^\+(page|layout)\.server\.ts$/;
const SERVER_ENDPOINT = /^\+server\.ts$/;

/**
 * @param leaf true for a route the demo actually ships, false for a directory
 *   carried only because a demo route sits beneath it. An ancestor contributes
 *   its layout and nothing else — copying its `+page.svelte` would publish a
 *   page with no load behind it.
 */
async function copyRouteDir(rel: string, leaf: boolean) {
	const from = `${SRC}/${rel}`;
	const to = `${OUT}/${rel}`;
	await mkdir(to, { recursive: true });

	for (const entry of await readdir(from, { withFileTypes: true })) {
		if (!entry.isFile()) continue;
		if (SERVER_FILE.test(entry.name) || SERVER_ENDPOINT.test(entry.name)) continue;
		if (!leaf && /^\+page\./.test(entry.name)) continue;
		await cp(`${from}/${entry.name}`, `${to}/${entry.name}`);
	}
}

/** The generated `+page.ts`: the demo's half of the binding. */
function pageModule(): string {
	return `// Generated by scripts/demo-build.ts — do not edit.
import { getDemoContext } from '$lib/demo/context';
import { base } from '$app/paths';
import * as h from './handlers';

export const ssr = false;
export const prerender = false;

export const load = async (event: Parameters<typeof h.load>[1]) =>
	h.load(await getDemoContext(base), event);
`;
}

async function main() {
	await rm(`${ROOT}/.demo`, { recursive: true, force: true });
	await mkdir(OUT, { recursive: true });

	// Root-level shell: the layout, its stylesheet, and the error page.
	for (const f of ['+layout.svelte', 'layout.css', '+error.svelte']) {
		if (existsSync(`${SRC}/${f}`)) await cp(`${SRC}/${f}`, `${OUT}/${f}`);
	}

	// Every ancestor of a demo route needs its layout carried across too.
	const dirs = new Set<string>();
	for (const rel of DEMO_ROUTES) {
		const parts = rel.split('/');
		for (let i = 1; i <= parts.length; i++) dirs.add(parts.slice(0, i).join('/'));
	}

	for (const rel of [...dirs].sort()) {
		if (!existsSync(`${SRC}/${rel}`)) continue;
		if (!(await stat(`${SRC}/${rel}`)).isDirectory()) continue;
		await copyRouteDir(rel, DEMO_ROUTES.includes(rel));
	}

	// Generate the page binding for each demo route that has neutral handlers.
	// A route with neither handlers.ts nor a +page.server.ts needs no load at
	// all (settings/help is static), and is shipped as-is.
	for (const rel of DEMO_ROUTES) {
		if (existsSync(`${SRC}/${rel}/handlers.ts`)) {
			await writeFile(`${OUT}/${rel}/+page.ts`, pageModule());
		} else if (existsSync(`${SRC}/${rel}/+page.server.ts`)) {
			throw new Error(
				`demo: ${rel} still has a +page.server.ts — convert it before adding it here`
			);
		}
	}

	// The root page: the server build redirects to the active workspace; the demo
	// has exactly one, and its slug is only known once the seed is open.
	await writeFile(
		`${OUT}/+page.ts`,
		`// Generated by scripts/demo-build.ts — do not edit.
import { redirect } from '@sveltejs/kit';
import { base } from '$app/paths';
import { getDemoContext } from '$lib/demo/context';

export const ssr = false;
export const prerender = false;

export const load = async () => {
	const ctx = await getDemoContext(base);
	redirect(307, \`\${base}/w/\${ctx.workspace.slug}/purchases\`);
};
`
	);

	// Every route's actions, registered up front.
	//
	// Lazily registering from each +page.ts only covered routes whose module had
	// already loaded — and forms routinely target another route: the ledger's
	// inline Approve posts to `purchases/<id>?/approve` from `purchases`. Those
	// found an empty registry and failed with "no actions registered".
	const withActions: string[] = [];
	for (const rel of DEMO_ROUTES) {
		const handlers = `${SRC}/${rel}/handlers.ts`;
		if (!existsSync(handlers)) continue;
		if (!(await readFile(handlers, 'utf8')).includes('export const actions')) continue;
		withActions.push(rel);
	}
	await writeFile(
		`${OUT}/w/[workspace]/demo-actions.ts`,
		`// Generated by scripts/demo-build.ts — do not edit.
import { registerDemoActions } from '$lib/demo/actions';
${withActions.map((rel, i) => `import * as h${i} from './${rel.split('/').slice(2).join('/')}${rel.split('/').length > 2 ? '/' : ''}handlers';`).join('\n')}

export function registerAll(): void {
${withActions.map((rel, i) => `\tregisterDemoActions('/${rel}', h${i}.actions);`).join('\n')}
}
`
	);

	// The workspace layout's data comes from +layout.server.ts on the server.
	await writeFile(
		`${OUT}/w/[workspace]/+layout.ts`,
		`// Generated by scripts/demo-build.ts — do not edit.
import { base } from '$app/paths';
import { getDemoContext } from '$lib/demo/context';
import { installDemoEndpoints } from '$lib/demo/endpoints';
import { registerAll } from './demo-actions';
import { listWorkspacesForUser } from '$lib/repo/workspaces';

export const ssr = false;
export const prerender = false;

// Both before any load runs: every route's form actions become reachable from
// any page, and the app's own fetches to /w/<slug>/... are answered locally
// rather than by the static host.
registerAll();
installDemoEndpoints(base);

export const load = async ({ params }: { params: { workspace: string } }) => {
	const { db, user, workspace, member } = await getDemoContext(base);
	const memberships = await listWorkspacesForUser(db, user.id);
	return {
		user: {
			id: user.id,
			displayName: user.displayName,
			avatarBlobId: user.avatarBlobId,
			avatarSource: user.avatarSource
		},
		workspace: {
			id: workspace.id,
			slug: params.workspace,
			name: workspace.name,
			currency: workspace.currency,
			timezone: workspace.timezone,
			accentColor: workspace.accentColor,
			assistEnabled: false
		},
		member: { id: member.id, role: member.role },
		workspaces: memberships.map((m) => ({
			slug: m.workspace.slug,
			name: m.workspace.name,
			accentColor: m.workspace.accentColor
		}))
	};
};
`
	);

	console.log(`demo routes generated at .demo/routes (${DEMO_ROUTES.length} page route(s))`);
}

main().catch((e) => {
	console.error('demo-build failed:', e?.message ?? e);
	process.exit(1);
});
